import "~/styles/globals.css";
import { TRPCProvider } from './_trpc/Provider';
import {ThemeProvider} from "../components/theme-provider"
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'

import { type Metadata } from "next";
import { Geist } from "next/font/google";

import { TRPCReactProvider } from "~/trpc/react";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
        <ClerkProvider>
    <html lang="en" className={`${geist.variable}`} suppressHydrationWarning>
      <body>
        <ThemeProvider  attribute="class"
        defaultTheme="system"
        enableSystem
        disableTransitionOnChange>
              <SignedOut>
              <SignInButton />
              <SignUpButton>
                <button className="bg-[#6c47ff] text-white rounded-full font-medium text-sm sm:text-base h-10 sm:h-12 px-4 sm:px-5 cursor-pointer">
                  Sign Up
                </button>
         </SignUpButton>
            </SignedOut>
            <SignedIn>
            </SignedIn>
            <TRPCReactProvider>{children}</TRPCReactProvider>
            </ThemeProvider>
      </body>
    </html>
        </ClerkProvider>
  );
}
